# Generated by Django 6.0.6 on 2026-06-23 09:11

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='location_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
