# Generated by Django 6.0.6 on 2026-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_location_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
